In [ ]:
zimport numpy as np
import random
from timeit import timeit
#Define addition functions
def add_python(Z1, Z2):
  return [z1 + z2 for z1, z2 in zip(Z1, Z2)]
def add_numpy(Z1, Z2):
  return np.add(Z1, Z2)
#Generate larger random sample data
size = 100000 #Increased size for more pronounced difference
Z1_list = random.sample(range(size + 1), size)
Z2_list = random.sample(range(size + 1), size)
Z1_np = np.array(Z1_list)
Z2_np = np.array(Z2_list)
#Time the execution of each function
python_time = timeit("add_python(Z1_list, Z2_list)", globals=globals(), number=100)
numpy_time = timeit("add_numpy(Z1_np, Z2_np)", globals=globals(), number=100)
#print results
print(f"Pure Python addition:{python_time:.6f} seconds per loop")
print(f"Numpy addition:{numpy_time:.6f} seconds per loop")

Pure Python addition:2.096264 seconds per loop
Numpy addition:0.010409 seconds per loop


In [ ]:
np.zeros((6,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
array_0d = np . array (5)
array_1d = np . array ([1 , 2 , 3 , 4 , 5])
array_2d = np . array ([[1 , 2 , 3] , [4 , 5 , 6]])
array_3d = np . array ([[[1 , 2] , [3 , 4]] , [[5 , 6] , [7 , 8]]]) # Changed [7 ,] to [7 , 8] to fix the shape inconsistency

for i , arr in enumerate ([ array_0d , array_1d , array_2d ,
array_3d ]) :
 print ( f"{i}D Array :\n{arr }\nShape : {arr. shape }\n")

0D Array :
5
Shape : ()

1D Array :
[1 2 3 4 5]
Shape : (5,)

2D Array :
[[1 2 3]
 [4 5 6]]
Shape : (2, 3)

3D Array :
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape : (2, 2, 2)



In [ ]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = array.reshape(3, 2)

print("Original shape: ", array.shape, "\nReshaped shape: ", reshaped_array.shape)
print(reshaped_array.shape)


Original shape:  (2, 3) 
Reshaped shape:  (3, 2)
(3, 2)


In [ ]:
x = range(1, 11)
print(list(x))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
print(np.linspace(1, 10, 7))
print(np.linspace(1, 10, 7, endpoint=False))

[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]


In [ ]:
identity_matrix = np.eye(6)
print(identity_matrix)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
arr1= np.array([[1, 2], [3, 4]])
arr2= np.array([[5, 6], [7, 8]])

hstacked = np.hstack((arr1, arr2))
vstacked = np.vstack((arr1, arr2))

print(hstacked, "\n", vstacked)

[[1 2 5 6]
 [3 4 7 8]] 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
concat_axis0 = np.concatenate((arr1, arr2), axis=0 )
concat_axis1 = np.concatenate((arr1, arr2), axis=1 )

print(concat_axis0, concat_axis1,)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] [[1 2 5 6]
 [3 4 7 8]]


In [2]:
import numpy as np

arr1d = np.array([0, 1, 2, 3, 4, 5])
arr2d = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr3d = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]], [[8,9], [10, 11]]])
print("Basic:", arr1d[1:4], arr2d[1:3, 0:2], arr3d[1:2, 0:2,1:2])
print("Step:", arr1d[1:5:2], arr2d[::2, 1::2], arr3d[::2,::2, 1::2])

Basic: [1 2 3] [[3 4]
 [6 7]] [[[5]
  [7]]]
Step: [1 3] [[1]
 [7]] [[[1]]

 [[9]]]


In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Add:", np.add(arr1, arr2))
print("Subtract:", np.subtract(arr1, arr2))
print("Exp:", np.exp(arr1))

Add: [5 7 9]
Subtract: [-3 -3 -3]
Exp: [ 2.71828183  7.3890561  20.08553692]


In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
result_dot = np.dot(A, B)
print("Result with np.dot:\n", result_dot)

Result with np.dot:
 [[ 58  64]
 [139 154]]


In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
result_at = A @ B
print("Result with @ operator:\n", result_at)
result_matmul = np.matmul(A, B)
print("Result with np.matmul:\n", result_matmul)

Result with @ operator:
 [[ 58  64]
 [139 154]]
Result with np.matmul:
 [[ 58  64]
 [139 154]]


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
print("Inverse:\n", np.linalg.inv(A))
print("Determinant:", np.linalg.det(A))
print("Frobenius Norm:", np.linalg.norm(A, 'fro'))
print("2-Norm (Euclidean):", np.linalg.norm(A))
print("Solution x:", np.linalg.solve(A, B))

Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Frobenius Norm: 5.477225575051661
2-Norm (Euclidean): 5.477225575051661
Solution x: [-4.   4.5]
