Problem - 1: Array Creation:

In [ ]:
import numpy as np

arr1 = np.empty((2, 2))
print("1. Empty array:\n", arr1)


arr2 = np.ones((4, 2))
print("\n2. Ones array:\n", arr2)


arr3 = np.full((3, 3), 7)
print("\n3. Full array (fill=7):\n", arr3)


a = np.array([[1, 2], [3, 4]])
arr4 = np.zeros_like(a)
print("\n4. Zeros like array a:\n", arr4)


arr5 = np.ones_like(a)
print("\n5. Ones like array a:\n", arr5)


new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print("\n6. List to numpy array:\n", arr6)


1. Empty array:
 [[2.99034379e-315 0.00000000e+000]
 [6.54857099e-310 6.54857106e-310]]

2. Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array (fill=7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like array a:
 [[0 0]
 [0 0]]

5. Ones like array a:
 [[1 1]
 [1 1]]

6. List to numpy array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [ ]:

arr1 = np.arange(10, 50)
print("\n1. Array 10 to 49:\n", arr1)


arr2 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix 0 to 8:\n", arr2)


arr3 = np.eye(3)
print("\n3. Identity matrix:\n", arr3)


arr4 = np.random.random(30)
print("\n4. Random array:\n", arr4)
print("Mean:", arr4.mean())


arr5 = np.random.random((10, 10))
print("\n5. Min:", arr5.min(), " Max:", arr5.max())


arr6 = np.zeros(10)
arr6[4] = 1
print("\n6. Replace 5th element with 1:\n", arr6)


arr7 = np.array([1, 2, 0, 0, 4, 0])
print("\n7. Reversed array:\n", arr7[::-1])


arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("\n8. Border 1 inside 0:\n", arr8)

arr9 = np.zeros((8, 8))
arr9[1::2, ::2] = 1
arr9[::2, 1::2] = 1
print("\n9. Checkerboard:\n", arr9)



1. Array 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array:
 [0.74234982 0.31487048 0.83404843 0.94459976 0.98417814 0.90172235
 0.86594854 0.14029509 0.6285171  0.85705981 0.34891023 0.63330888
 0.31509806 0.95135326 0.62336267 0.43095398 0.07951456 0.14471504
 0.88598654 0.9600789  0.34574656 0.9798543  0.00146511 0.57219666
 0.83781905 0.39104949 0.05419959 0.25536666 0.74280659 0.87256878]
Mean: 0.5879981474054793

5. Min: 0.028558984994153436  Max: 0.9793822631951563

6. Replace 5th element with 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array:
 [0 4 0 0 2 1]

8. Border 1 inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0.

Problem - 3: Array Operations:

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("\n1. Add:\n", x + y)
print("\n2. Subtract:\n", x - y)
print("\n3. Multiply by 3:\n", x * 3)
print("\n4. Square:\n", x ** 2)

print("\n5. Dot(v, w):", np.dot(v, w))
print("Dot(x, v):", np.dot(x, v))
print("Dot(x, y):\n", np.dot(x, y))

print("\n6. Concatenate x and y (rows):\n", np.concatenate((x, y), axis=0))
print("Concatenate v & w (columns):\n", np.vstack((v, w)))

print("\n7. Concatenate x and v (ERROR expected):")
print("Cannot concatenate because shapes do not match (2x2 vs length 2).")



1. Add:
 [[ 6  8]
 [10 13]]

2. Subtract:
 [[-4 -4]
 [-4 -3]]

3. Multiply by 3:
 [[ 3  6]
 [ 9 15]]

4. Square:
 [[ 1  4]
 [ 9 25]]

5. Dot(v, w): 219
Dot(x, v): [29 77]
Dot(x, y):
 [[19 22]
 [50 58]]

6. Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v & w (columns):
 [[ 9 10]
 [11 12]]

7. Concatenate x and v (ERROR expected):
Cannot concatenate because shapes do not match (2x2 vs length 2).


Problem - 4: Matrix Operations:

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
print("\n1. A * A^-1:\n", A @ A_inv)

AB = A @ B
BA = B @ A
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB != BA =", not np.allclose(AB, BA))

lhs = (A @ B).T
rhs = B.T @ A.T
print("\n3. (AB)^T:\n", lhs)
print("B^T A^T:\n", rhs)




1. A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB != BA = True

3. (AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


Linear equation using Inverse Methods.

In [ ]:
A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

X = np.linalg.solve(A, B)
print("\nSolution to AX = B:\n x =", X[0], " y =", X[1], " z =", X[2])



Solution to AX = B:
 x = 2.0  y = 1.0000000000000002  z = -2.0
